
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  8 2026 02:12:35 EDT (Aug  8 2026 06:12:35 UTC)

// Verification Directory fv/i2c_master 

module i2c_master(clk, reset_n, start, addr, data, scl, sda, busy);
  input clk, reset_n, start;
  input [6:0] addr;
  input [7:0] data;
  output scl, busy;
  inout sda;
  wire clk, reset_n, start;
  wire [6:0] addr;
  wire [7:0] data;
  wire scl, busy;
  wire sda;
  wire [2:0] bit_cnt;
  wire [7:0] clk_div;
  wire [2:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_106, sda_oe, sda_out;
  wire tick;
  DFFSHQX1 sda_out_reg(.SN (reset_n), .CK (clk), .D (n_86), .Q
       (sda_out));
  NAND4XL g1299__2398(.A (n_11), .B (n_71), .C (n_83), .D (n_84), .Y
       (n_86));
  SDFFRHQX1 \bit_cnt_reg[1] (.RN (reset_n), .CK (clk), .D (bit_cnt[1]),
       .SI (n_23), .SE (n_85), .Q (bit_cnt[1]));
  SDFFRHQX1 \bit_cnt_reg[2] (.RN (reset_n), .CK (clk), .D (bit_cnt[2]),
       .SI (n_37), .SE (n_85), .Q (bit_cnt[2]));
  SDFFRHQX1 \bit_cnt_reg[0] (.RN (reset_n), .CK (clk), .D (bit_cnt[0]),
       .SI (n_60), .SE (n_85), .Q (bit_cnt[0]));
  SDFFRHQX1 \clk_div_reg[7] (.RN (reset_n), .CK (clk), .D (n_0), .SI
       (clk_div[7]), .SE (n_80), .Q (clk_div[7]));
  AND2X1 g1308__5107(.A (n_73), .B (n_81), .Y (n_84));
  SDFFSHQX1 sda_oe_reg(.SN (reset_n), .CK (clk), .D (n_55), .SI
       (sda_oe), .SE (n_76), .Q (sda_oe));
  AOI211XL g1304__6260(.A0 (n_59), .A1 (data[0]), .B0 (n_66), .C0
       (n_75), .Y (n_83));
  DFFSHQX1 scl_reg(.SN (reset_n), .CK (clk), .D (n_77), .Q (scl));
  SDFFRHQX1 \state_reg[0] (.RN (reset_n), .CK (clk), .D (state[0]), .SI
       (n_28), .SE (n_82), .Q (state[0]));
  SDFFRHQX1 \clk_div_reg[6] (.RN (reset_n), .CK (clk), .D (n_79), .SI
       (clk_div[6]), .SE (n_78), .Q (clk_div[6]));
  SDFFRHQX1 \state_reg[2] (.RN (reset_n), .CK (clk), .D (state[2]), .SI
       (n_41), .SE (n_82), .Q (state[2]));
  SDFFRHQX1 \state_reg[1] (.RN (reset_n), .CK (clk), .D (state[1]), .SI
       (n_21), .SE (n_82), .Q (state[1]));
  AOI33XL g1326__4319(.A0 (n_19), .A1 (bit_cnt[1]), .A2 (n_65), .B0
       (bit_cnt[2]), .B1 (n_36), .B2 (n_63), .Y (n_81));
  OAI211XL g1310__8428(.A0 (n_35), .A1 (n_38), .B0 (n_42), .C0 (n_72),
       .Y (n_85));
  OR2X1 g1359__5526(.A (n_79), .B (n_78), .Y (n_80));
  OAI211XL g1300__6783(.A0 (n_67), .A1 (scl), .B0 (n_30), .C0 (n_68),
       .Y (n_77));
  SDFFRHQX1 \clk_div_reg[5] (.RN (reset_n), .CK (clk), .D (n_70), .SI
       (clk_div[5]), .SE (n_69), .Q (clk_div[5]));
  AOI21XL g1317__3680(.A0 (n_43), .A1 (n_51), .B0 (n_61), .Y (n_76));
  OAI33XL g1324__1617(.A0 (n_26), .A1 (n_16), .A2 (n_74), .B0 (n_64),
       .B1 (n_18), .B2 (n_74), .Y (n_75));
  SDFFRHQX1 busy_reg(.RN (reset_n), .CK (clk), .D (n_54), .SI (busy),
       .SE (n_73), .Q (busy));
  AOI33XL g1325__2802(.A0 (n_106), .A1 (scl), .A2 (n_58), .B0
       (state[1]), .B1 (n_5), .B2 (n_39), .Y (n_72));
  AOI33XL g1313__1705(.A0 (n_50), .A1 (addr[0]), .A2 (n_62), .B0
       (state[0]), .B1 (sda_out), .B2 (n_25), .Y (n_71));
  OR2X1 g1360__5122(.A (n_70), .B (n_69), .Y (n_78));
  SDFFRHQX1 \clk_div_reg[4] (.RN (reset_n), .CK (clk), .D (n_57), .SI
       (clk_div[4]), .SE (n_56), .Q (clk_div[4]));
  NAND4XL g1318__8246(.A (n_44), .B (n_45), .C (n_34), .D (n_52), .Y
       (n_82));
  NAND2XL g1302__7098(.A (scl), .B (n_67), .Y (n_68));
  NOR4BXL g1330__6131(.AN (n_65), .B (bit_cnt[1]), .C (n_64), .D
       (n_13), .Y (n_66));
  AO22X1 g1339__1881(.A0 (data[4]), .A1 (n_65), .B0 (addr[4]), .B1
       (n_62), .Y (n_63));
  NOR2XL g1319__5115(.A (n_22), .B (n_67), .Y (n_61));
  DFFRHQX1 \clk_div_reg[2] (.RN (reset_n), .CK (clk), .D (n_48), .Q
       (clk_div[2]));
  OAI21XL g1306__7482(.A0 (n_49), .A1 (bit_cnt[0]), .B0 (n_40), .Y
       (n_60));
  NOR2BXL g1331__4733(.AN (n_65), .B (n_58), .Y (n_59));
  OR2X1 g1361__6161(.A (n_57), .B (n_56), .Y (n_69));
  SDFFRHQX1 \clk_div_reg[3] (.RN (reset_n), .CK (clk), .D (n_32), .SI
       (clk_div[3]), .SE (n_31), .Q (clk_div[3]));
  NAND2XL g1309__9315(.A (n_14), .B (n_53), .Y (n_55));
  NOR2BXL g1307__9945(.AN (start), .B (n_53), .Y (n_54));
  NAND4XL g1340__2883(.A (state[1]), .B (scl), .C (n_51), .D (n_50), .Y
       (n_52));
  OR2X1 g1328__2346(.A (n_10), .B (n_49), .Y (n_67));
  NOR2XL g1298__1666(.A (n_24), .B (n_47), .Y (n_48));
  NOR2XL g1297__7410(.A (clk_div[0]), .B (n_47), .Y (n_46));
  AOI32XL g1323__6417(.A0 (n_7), .A1 (state[0]), .A2 (n_27), .B0
       (n_12), .B1 (n_51), .Y (n_45));
  NAND2XL g1322__5477(.A (n_51), .B (n_49), .Y (n_73));
  INVXL g1348(.A (n_62), .Y (n_74));
  OAI211XL g1329__2398(.A0 (state[0]), .A1 (start), .B0 (tick), .C0
       (n_43), .Y (n_44));
  NAND3XL g1327__5107(.A (tick), .B (state[0]), .C (n_43), .Y (n_42));
  NAND2XL g1303__6260(.A (n_33), .B (n_40), .Y (n_41));
  NOR2XL g1332__4319(.A (n_38), .B (n_50), .Y (n_39));
  OAI211XL g1314__8428(.A0 (n_36), .A1 (n_17), .B0 (n_35), .C0 (n_58),
       .Y (n_37));
  OR3XL g1338__5526(.A (n_38), .B (n_33), .C (n_58), .Y (n_34));
  OR2X1 g1362__6783(.A (n_32), .B (n_31), .Y (n_56));
  NOR2XL g1350__3680(.A (n_20), .B (n_30), .Y (n_62));
  NOR2XL g1354__1617(.A (state[1]), .B (n_30), .Y (n_65));
  NOR2BXL g1305__1705(.AN (n_27), .B (state[0]), .Y (n_28));
  AOI222XL g1337__5122(.A0 (addr[2]), .A1 (n_2), .B0 (addr[6]), .B1
       (bit_cnt[2]), .C0 (bit_cnt[0]), .C1 (addr[3]), .Y (n_26));
  NAND2XL g1334__8246(.A (n_27), .B (n_25), .Y (n_49));
  MXI2XL g1364__7098(.A (n_15), .B (n_4), .S0 (clk_div[2]), .Y (n_24));
  NAND2XL g1315__6131(.A (n_35), .B (n_8), .Y (n_23));
  NAND2XL g1320__1881(.A (n_22), .B (n_43), .Y (n_53));
  AND4X1 g1301__5115(.A (clk_div[2]), .B (n_32), .C (n_3), .D (n_6), .Y
       (n_47));
  OAI32XL g1312__7482(.A0 (state[0]), .A1 (state[2]), .A2 (n_20), .B0
       (n_22), .B1 (state[1]), .Y (n_21));
  MX4XL g1346__4733(.A (data[2]), .B (data[6]), .C (data[3]), .D
       (data[7]), .S0 (bit_cnt[2]), .S1 (bit_cnt[0]), .Y (n_19));
  AOI32XL g1336__6161(.A0 (n_17), .A1 (addr[1]), .A2 (n_16), .B0
       (bit_cnt[2]), .B1 (addr[5]), .Y (n_18));
  INVXL g1349(.A (n_58), .Y (n_50));
  OR2X1 g1321__9315(.A (n_20), .B (n_35), .Y (n_40));
  NAND2XL g1363__9945(.A (clk_div[2]), .B (n_15), .Y (n_31));
  SDFFRHQX1 \clk_div_reg[1] (.RN (reset_n), .CK (clk), .D (clk_div[0]),
       .SI (n_1), .SE (clk_div[1]), .Q (clk_div[1]));
  NAND2XL g1356__2883(.A (n_14), .B (n_51), .Y (n_30));
  MXI2XL g1345__2346(.A (data[5]), .B (data[1]), .S0 (n_17), .Y (n_13));
  INVXL g1341(.A (n_12), .Y (n_27));
  INVXL g1342(.A (n_25), .Y (n_43));
  NAND2XL g1351__1666(.A (n_17), .B (n_36), .Y (n_58));
  AOI32XL g1316__7410(.A0 (n_22), .A1 (sda_out), .A2 (scl), .B0 (n_10),
       .B1 (sda_out), .Y (n_11));
  AOI21XL g1367__6417(.A0 (bit_cnt[1]), .A1 (bit_cnt[0]), .B0 (n_36),
       .Y (n_8));
  INVXL g1352(.A (n_7), .Y (n_38));
  NOR4XL g1311__5477(.A (clk_div[4]), .B (clk_div[5]), .C (clk_div[6]),
       .D (clk_div[7]), .Y (n_6));
  NAND2XL g1344__2398(.A (n_20), .B (n_5), .Y (n_25));
  NAND2XL g1335__5107(.A (state[0]), .B (n_5), .Y (n_35));
  NOR2XL g1343__6260(.A (n_20), .B (n_5), .Y (n_12));
  NOR2XL g1353__4319(.A (n_10), .B (n_14), .Y (n_7));
  INVXL g1365(.A (n_4), .Y (n_15));
  NAND2XL g1347__8428(.A (state[2]), .B (n_20), .Y (n_33));
  NOR2XL g1358__5526(.A (state[0]), .B (n_10), .Y (n_51));
  TBUFXL g1__6783(.A (sda_out), .OE (sda_oe), .Y (sda));
  NOR2XL g1366__3680(.A (clk_div[0]), .B (clk_div[1]), .Y (n_3));
  NOR2XL g1355__1617(.A (bit_cnt[0]), .B (bit_cnt[2]), .Y (n_2));
  NAND2XL g1368__2802(.A (clk_div[0]), .B (clk_div[1]), .Y (n_4));
  NOR2XL g1369__1705(.A (bit_cnt[0]), .B (bit_cnt[1]), .Y (n_36));
  INVXL g1370(.A (clk_div[7]), .Y (n_0));
  INVXL g1375(.A (bit_cnt[1]), .Y (n_16));
  INVXL g1380(.A (clk_div[6]), .Y (n_79));
  INVXL g1371(.A (clk_div[4]), .Y (n_57));
  INVXL g1382(.A (scl), .Y (n_14));
  INVXL g1383(.A (state[1]), .Y (n_20));
  INVXL g1376(.A (bit_cnt[0]), .Y (n_64));
  INVXL g1372(.A (clk_div[5]), .Y (n_70));
  INVXL g1379(.A (clk_div[3]), .Y (n_32));
  INVXL g1378(.A (bit_cnt[2]), .Y (n_17));
  INVXL g1374(.A (state[2]), .Y (n_5));
  INVXL g1377(.A (state[0]), .Y (n_22));
  DFFRX1 \clk_div_reg[0] (.RN (reset_n), .CK (clk), .D (n_46), .Q
       (clk_div[0]), .QN (n_1));
  DFFRX1 tick_reg(.RN (reset_n), .CK (clk), .D (n_47), .Q (tick), .QN
       (n_10));
  NOR2BXL g2(.AN (n_51), .B (n_33), .Y (n_106));
endmodule

